### ISSUE TITLE
Error [org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor] - No root resource matching request path /route/restservice/getQuote has been found, Relative Path: /restservice/getQuote. Please enable FINE/TRACE log level for more details.

### ISSUE THREAD

**Issue by szarekar** [gcolman/FuseExamples#1]
Hi i am getting this error on calling

http://localhost:9090/route/restservice/getQuote

from POSTMAN REST CLIENT

ERROR

WARN [org.apache.cxf.jaxrs.interceptor.JAXRSInInterceptor] - No root resource matching request path /route/restservice/getQuote has been found, Relative Path: /restservice/getQuote. Please enable FINE/TRACE log level for more details.
qtp487436278-16 WARN [org.apache.cxf.jaxrs.impl.WebApplicationExceptionMapper] - javax.ws.rs.NotFoundException: HTTP 404 Not Found

**Comment by gcolman** [comment]
Check that your cxfrs server definition has the  /route path (or remove it)
cxf:rsServer id="restFrontend" address="http://localhost:9090/route" serviceClass="com.mycompany.rest.GetQuoteResource" 

Cheers
Graeme.

**Comment by szarekar** [comment]
Yes It is the same   . I checked.

<cxf:rsServer id="restFrontend" address="http://localhost:9090/route" serviceClass="com.mycompany.rest.GetQuoteResource" />

**Comment by gcolman** [comment]
I put a video together that builds up this example if you want to take a look. https://www.youtube.com/watch?v=_QYeuJUvTEI

If this does not help then let me know aand I can pick up again tomorrow.

**Comment by szarekar** [comment]
I got a fresh download and created a new project . Getting this error now

org.apache.camel.component.http.HttpOperationFailedException: HTTP operation failed invoking http://www.webservicex.net/stockquote.asmx with statusCode: 415
	at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:228)
	at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:156)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:51)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110)
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105)
	at org.apache.camel.processor.MulticastProcessor.doProcessParallel(MulticastProcessor.java:712)
	at org.apache.camel.processor.MulticastProcessor.access$200(MulticastProcessor.java:83)
	at org.apache.camel.processor.MulticastProcessor$1.call(MulticastProcessor.java:293)
	at org.apache.camel.processor.MulticastProcessor$1.call(MulticastProcessor.java:278)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)



#######################  blueprint.xml file

<cxf:rsServer id="restFrontend" address="http://localhost:9090/route" serviceClass="com.mycompany.rest.GetQuoteResource" />   
	<bean id="aggregateOrdersBean" class="com.mycompany.beans.AggregateOrders"/>

	<camelContext xmlns="http://camel.apache.org/schema/blueprint">
    <endpoint uri="http://www.webservicex.net/stockquote.asmx" id="callQuoteWebService"/>
    <route id="Main Route">
        <from uri="cxfrs:bean:restFrontend"/>
        <log message="Rest endpoint body = ${body}"/>
        <to uri="direct:setHeaders"/>
        <split parallelProcessing="true">
            <xpath>/quote/company</xpath>
            <log message="Split body = ${body}"/>
            <to uri="direct:serviceProxy"/>
            <log loggingLevel="INFO" message="Message = ${body}"/>
        </split>
    </route>
    <route id="setHeaders">
        <from uri="direct:setHeaders"/>
        <removeHeaders pattern="CamelHttp*"/>
        <setHeader headerName="numorders">
            <xpath>/quote/@numorders</xpath>
        </setHeader>
        <setHeader headerName="orderid">
            <xpath>/quote/@orderid</xpath>
        </setHeader>
    </route>
    <route id="Serviceproxy">
        <from uri="direct:serviceProxy"/>
        <to uri="xslt:xsl/quote.xsl"/>
        <to ref="callQuoteWebService"/>
        <setBody>
            <xpath resultType="java.lang.String">/soap:Envelope/soap:Body/ws:GetQuoteResponse/ws:GetQuoteResult</xpath>
        </setBody>
    </route>

**Comment by szarekar** [comment]
I got fresh download and build this project again.Getting this error now
org.apache.camel.component.http.HttpOperationFailedException: HTTP operation failed invoking http://www.webservicex.net/stockquote.asmx with statusCode: 415
    at org.apache.camel.component.http.HttpProducer.populateHttpOperationFailedException(HttpProducer.java:228)
    at org.apache.camel.component.http.HttpProducer.process(HttpProducer.java:156)
    at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
    at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110)
    at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
    at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
    at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:51)
    at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110)
    at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72)
    at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:118)
    at org.apache.camel.processor.Pipeline.process(Pipeline.java:80)
    at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398)
    at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191)
    at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105)
    at org.apache.camel.processor.MulticastProcessor.doProcessParallel(MulticastProcessor.java:712)
    at org.apache.camel.processor.MulticastProcessor.access$200(MulticastProcessor.java:83)
    at org.apache.camel.processor.MulticastProcessor$1.call(MulticastProcessor.java:293)
    at org.apache.camel.processor.MulticastProcessor$1.call(MulticastProcessor.java:278)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
    at java.lang.Thread.run(Thread.java:662)

###############  have attached snapshot of my blueprint.xml file
![blueprint](https://cloud.githubusercontent.com/assets/11322386/6542046/eea38324-c4b1-11e4-832e-45c26b1e2f85.png)

**Comment by gcolman** [comment]
Strange, I have just done the same and works fine. The HTTP 415 indicates that the content type is not the same as the end service is expecting. Trey setting the endpoint explicitly be adding something like:

<setHeader id="HttpHeaders.CONTENT_TYPE">
    <simple "application/xml"/>
</setHeader

**Comment by szarekar** [comment]
i added above in  blueprint.xml file. I am still getting the same error
<route id="Serviceproxy">
        <from uri="direct:serviceProxy"/>
        <to uri="xslt:xsl/quote.xsl"/>
        <to ref="callQuoteWebService"/>
        <setHeader headerName="HttpHeaders.CONTENT_TYPE">
            <simple>application/xml</simple>
        </setHeader>
        <setBody>
            <xpath resultType="java.lang.String">/soap:Envelope/soap:Body/ws:GetQuoteResponse/ws:GetQuoteResult</xpath>
        </setBody>
    </route>

**Comment by diephil** [comment]
Hello, did you resolve this issue szarekar?
Best regards
